server:
  port: 13100
  address: 0.0.0.0

spring:

  application:
    name: MessageNotificationMicroservice
  mail:
    host: smtp.163.com
    username: tjtestfundsys@163.com
    password: KXYUXPYJIQRWHDPK
    # SSL Config
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8,vEthernet (WSL)'
    nacos:
      server-addr : 117.50.181.249:8848
      discovery:
        ip: 47.96.238.150
        port: 13100
        username: nacos
        password: nacos
        namespace: public

